In [1]:
import numpy as np
a=np.array([1,7,8,2])
a+1

array([2, 8, 9, 3])

In [2]:
a**2

array([ 1, 49, 64,  4], dtype=int32)

In [3]:
ae=np.array([3,2,1,4])+1
ae

array([4, 3, 2, 5])

In [4]:
ae-a

array([ 3, -4, -6,  3])

In [8]:
b=np.ones((4,4))+1
b

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [9]:
a-b

array([[-1.,  5.,  6.,  0.],
       [-1.,  5.,  6.,  0.],
       [-1.,  5.,  6.,  0.],
       [-1.,  5.,  6.,  0.]])

In [10]:
a*b

array([[ 2., 14., 16.,  4.],
       [ 2., 14., 16.,  4.],
       [ 2., 14., 16.,  4.],
       [ 2., 14., 16.,  4.]])

In [12]:
er=np.diag([1,2,3,4])
print(er)
print("*********************")
print(er*er)
print("*********************")
print(er.dot(er))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
*********************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*********************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [13]:
np.diag(er*er)

array([ 1,  4,  9, 16])

In [14]:
ce=np.array([1,7,5,9])
ck=np.array([1,6,5,9])
ce==ck

array([ True, False,  True,  True])

In [17]:
cz=np.array([1,7,5,9])
print(np.array_equal(ce,ck))
print(np.array_equal(ce,cz))

False
True


In [19]:
print(ce>ck)
print(ce>=ck)
print(ce==cz)
print(ce&ck)
print(ce|ck)

[False  True False False]
[ True  True  True  True]
[ True  True  True  True]
[1 6 5 9]
[1 7 5 9]


In [20]:
yt=np.array([1,1,0,0],dtype=bool)
yr=np.array([1,0,1,0],dtype=bool)
np.logical_and(yt,yr)

array([ True, False, False, False])

In [22]:
print(np.logical_and(yt,yr))
print(np.logical_or(yt,yr))

[ True False False False]
[ True  True  True False]


In [23]:
cf=np.array([True,False,True,False])
fd=np.array([True,True,False,False])
print(np.logical_and(cf,fd))
print(np.logical_or(cf,fd))

[ True False False False]
[ True  True  True False]


In [25]:
print(cf|fd)
print(cf&fd)

[ True  True  True False]
[ True False False False]


In [2]:
px=np.array([
    [1,2,3],
    [2,3,4]
])
ek=np.array([
    [5,6,7,8],
    [9,9,1,2],
    [2,1,7,8]
])
print(px.dot(ek))
print(ek.max)

[[29 27 30 36]
 [45 43 45 54]]
<built-in method max of numpy.ndarray object at 0x000001FFB2186E40>


In [29]:
ut=np.array([0,30,45,90])
print(np.sin(ut))

[ 0.         -0.98803162  0.85090352  0.89399666]


In [30]:
yy=np.array([0,10,100,2])
print(np.log(yy))

[      -inf 2.30258509 4.60517019 0.69314718]


C:\Users\ANKIT\.conda\envs\tensorflow_env\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


In [32]:
print(np.exp(yy))

[1.00000000e+00 2.20264658e+04 2.68811714e+43 7.38905610e+00]


In [33]:
te=np.array([1,4,5,7,8,9,3,2])
print(np.sum(te))

39


In [35]:
print(te.max())
print(te.min())
print(te.argmax())
print(te.argmin())

9
1
5
0


In [37]:
xo=np.array([
    [1,2,1],
    [1,7,8],
    [1,1,1]
])
print(xo.sum(axis=0))
print(xo.sum(axis=1))

[ 3 10 10]
[ 4 16  3]


In [39]:
print(np.any([False,False,False]))
print(np.any([True,False,False]))

False
True


In [41]:
print(np.all([False,False,False]))
print(np.all([True,False,False]))
print(np.any([True,True,True]))


False
False
True


In [46]:
cv=np.ones((50,50))
print(np.all(cv==cv))
print(np.all(cv!=0))
print(np.any(cv==cv))
print(np.any(cv!=1))

True
True
True
False


In [47]:
qq=np.array([1,2,3,4])
qqq=np.array([1,2,3,4])
qqqq=np.array([1,2,4,5])
((qq<=qqq)&(qqq<=qqqq)).all()

True

In [49]:
gt=np.ones((50,50))
gt.shape


(50, 50)

In [51]:
r=np.array([1,7,8])
rr=np.array([
    [1,5,3],
    [2,6,8]
])
print(r.mean())
print(np.median(r))
print(np.median(rr,axis=-1))
print(r.std())

5.333333333333333
7.0
[3. 6.]
3.0912061651652345


In [53]:
data=np.loadtxt('populations.txt')
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [55]:
data.shape

(21, 4)

In [58]:
year,hare,lynx,carrot=data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [61]:
new=data[:,1:]
new

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [62]:
new.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [63]:
#which species has highest population each year

np.argmax(new,axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [64]:
#which year has highest number of carrot populations?

new1=data[:,0:2]
new1

array([[ 1900., 30000.],
       [ 1901., 47200.],
       [ 1902., 70200.],
       [ 1903., 77400.],
       [ 1904., 36300.],
       [ 1905., 20600.],
       [ 1906., 18100.],
       [ 1907., 21400.],
       [ 1908., 22000.],
       [ 1909., 25400.],
       [ 1910., 27100.],
       [ 1911., 40300.],
       [ 1912., 57000.],
       [ 1913., 76600.],
       [ 1914., 52300.],
       [ 1915., 19500.],
       [ 1916., 11200.],
       [ 1917.,  7600.],
       [ 1918., 14600.],
       [ 1919., 16200.],
       [ 1920., 24700.]])

In [66]:
new1.max()

77400.0

In [68]:
q=np.tile(np.arange(0,40,10),(3,1))
print(q)
q=q.T
print(q)
print(q.shape)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
(4, 3)


In [69]:
r=np.array([0,1,2])
r

array([0, 1, 2])

In [70]:
q+r

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [72]:
 sa=np.arange(0,40,10);sa.shape

(4,)

In [73]:
sa=sa[:,np.newaxis]
print(sa)
sa.shape

[[ 0]
 [10]
 [20]
 [30]]


(4, 1)

In [74]:
sa+r

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [76]:
et=np.array([
    [5,3,2],
    [10,4,6],
    [1,7,9]
])
et.ravel()

array([ 5,  3,  2, 10,  4,  6,  1,  7,  9])

In [77]:
et.T.ravel()

array([ 5, 10,  1,  3,  4,  7,  2,  6,  9])

In [79]:
ex=et.reshape(3,3)
ex

array([[ 5,  3,  2],
       [10,  4,  6],
       [ 1,  7,  9]])

In [81]:
ex[0,0]=100
ex

array([[100,   3,   2],
       [ 10,   4,   6],
       [  1,   7,   9]])

In [82]:
et

array([[100,   3,   2],
       [ 10,   4,   6],
       [  1,   7,   9]])

In [85]:
an=np.zeros((2,3))
ann=an.T.reshape(2*3)
print(ann)
print("******************")
an[0,1]=10
print(an)
print(ann)


[0. 0. 0. 0. 0. 0.]
******************
[[ 0. 10.  0.]
 [ 0.  0.  0.]]
[0. 0. 0. 0. 0. 0.]


In [86]:
io=np.arange(4*3*5).reshape(4,3,5)
print(io)
print(io.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]

 [[45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
(4, 3, 5)


In [87]:
io[2,1,2]=100
io

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14]],

       [[ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34],
        [ 35,  36, 100,  38,  39],
        [ 40,  41,  42,  43,  44]],

       [[ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59]]])

In [92]:
iu=np.arange(4)
iu.resize((9,))
iu

array([0, 1, 2, 3, 0, 0, 0, 0, 0])

In [99]:
yy=np.array([
    [1,3,7],
    [9,3,6]
])

yy.sort(axis=0)
yy

array([[1, 3, 6],
       [9, 3, 7]])

In [100]:
gtr=np.array([1,7,5,9])
rre=np.argsort(gtr)
rre

array([0, 2, 1, 3], dtype=int64)

In [101]:
gtr[rre]

array([1, 5, 7, 9])

NameError: name 'xgboost' is not defined