In [1]:
import numpy as np
arr=np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [6]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr.ndim


2

In [2]:
arr.shape

(1, 3, 3)

In [12]:
ar=np.array([
    [1,2,3],
    [4,5,6]
])
ar



array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
ar.shape


(2, 3)

In [13]:
a=np.array([1,2,3,4])
a.shape

(4,)

In [17]:
len(arr)

3

In [18]:
c=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
c.ndim

3

In [20]:
c.shape

(2, 2, 2)

In [21]:
len(c)

2

In [22]:
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [23]:
b.shape

(5,)

In [27]:
u=np.linspace(3,9,20)

u

array([3.        , 3.31578947, 3.63157895, 3.94736842, 4.26315789,
       4.57894737, 4.89473684, 5.21052632, 5.52631579, 5.84210526,
       6.15789474, 6.47368421, 6.78947368, 7.10526316, 7.42105263,
       7.73684211, 8.05263158, 8.36842105, 8.68421053, 9.        ])

In [28]:
r=np.ones((3,2))
r

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
tr=np.ones((3,3,3))
tr

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [30]:
ee=np.zeros((4,3))
ee

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
ew=np.zeros((3,3,3))
ew

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [35]:
se=np.eye(3)
se

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
sr=np.eye(4)
sr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
ey=np.eye(3,4)
ey

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [40]:
ex=np.diag([2,3])
ex

array([[2, 0],
       [0, 3]])

In [41]:
ert=np.diag([5,3,1,6,9])
ert

array([[5, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 9]])

In [42]:
np.diag(arr)

array([1, 5, 9])

In [43]:
xz=np.random.rand(4)
xz

array([0.9175045 , 0.82098549, 0.61066536, 0.50904048])

In [44]:
cc=np.random.randn(4)
cc

array([-2.09480231,  0.39291412, -1.9434864 , -0.59649247])

In [45]:
cc.dtype

dtype('float64')

In [46]:
ert.dtype

dtype('int32')

In [47]:
a=np.arange(10,dtype='float32')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [48]:
ee.dtype

dtype('float64')

In [51]:
sd=np.array([1+2j,5+6j])
sd

array([1.+2.j, 5.+6.j])

In [52]:
sd.dtype

dtype('complex128')

In [58]:
cx=np.array([True,False,True,False])
cx

array([ True, False,  True, False])

In [59]:
cx.dtype

dtype('bool')

In [60]:
dt=np.array(["Ankit","Shrutika"])
dt

array(['Ankit', 'Shrutika'], dtype='<U8')

In [63]:
rt=np.array([
    [1,2,8],
    ['ankit','Lolo','Jio'],
    [True,False,True]
])
print(rt)

[['1' '2' '8']
 ['ankit' 'Lolo' 'Jio']
 ['True' 'False' 'True']]


In [65]:
ty=np.array([
    [True,'Ankit',False],
    [False,76,'Ankit'],
    [True,False,'ankit',79]
])
ty


array([list([True, 'Ankit', False]), list([False, 76, 'Ankit']),
       list([True, False, 'ankit', 79])], dtype=object)

In [66]:
ty.ndim

1

In [67]:
ty.shape

(3,)

In [68]:
len(ty)

3

In [69]:
fr=np.arange(11)
fr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
a[5]

5.0

In [73]:
fr[5]

5

In [74]:
fr[6]=1877
fr

array([   0,    1,    2,    3,    4,    5, 1877,    7,    8,    9,   10])

In [5]:
rew=np.diag([1,4,7])
rew

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 7]])

In [7]:
rew[0,1]=4
rew[0,2]=6
rew[1,0]=7
rew[1,2]=567
rew[2,2]=99
rew

array([[  1,   4,   6],
       [  7,   4, 567],
       [  0,   0,  99]])

In [9]:
oi=np.arange(10)
oi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
nh=np.arange(5)
oi[5:]=nh[::-1]
oi

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [12]:
nu=oi[::4]
nu

array([0, 4, 1])

In [13]:
np.shares_memory(oi,nu)

True

In [15]:
nu[2]=52
nu

array([ 0,  4, 52])

In [16]:
oi

array([ 0,  1,  2,  3,  4,  4,  3,  2, 52,  0])

In [18]:
gx=oi[::4].copy()
gx

array([ 0,  4, 52])

In [19]:
np.shares_memory(oi,gx)

False

In [21]:
ut=np.random.randint(0,21,18)
ut

array([ 4, 13,  6, 17, 11,  2,  2,  1, 20, 11, 11,  7,  8, 15, 12, 10, 13,
        3])

In [23]:
mask=(ut%2==0)
ex=ut[mask]
ex

array([ 4,  6,  2,  2, 20,  8, 12, 10])

In [26]:
ut[mask]=True
ut

array([ 1, 13,  1, 17, 11,  1,  1,  1,  1, 11, 11,  7,  1, 15,  1,  1, 13,
        3])

In [27]:
iu=np.arange(0,100,10)
iu

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
rets=iu<60
tr=iu[rets]
tr

array([ 0, 10, 20, 30, 40, 50])

In [33]:
tr[[2,3,4,5,1,]]

array([20, 30, 40, 50, 10])

In [34]:
tr[[5,1]]=89
tr

array([ 0, 89, 20, 30, 40, 89])

In [2]:
import tensorflow as tf
print("Tensorflow version: {}".format(tf.__version__))

Tensorflow version: 2.1.0


In [1]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'